/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function UnderWaterMountainSide(props) {
  const { nodes, materials } = useGLTF('../models/underWater-mountain-side.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
      />
    </group>
  )
}

useGLTF.preload('../models/underWater-mountain-side.glb')