/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: jeilocreativedesignworld (https://sketchfab.com/jeilocreativedesignworld)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cocacola-00824239737b4a4098893c25562daa9b
Title: Cocacola
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cocacola(props) {
  const { nodes, materials } = useGLTF('/cocacola.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.048, -0.256, 0.065]} scale={1.906}>
        <group position={[-0.001, 0.001, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.node_id6_Material_32_0.geometry}
            material={materials.Material_32}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.node_id6_Material_32_0_1.geometry}
            material={materials.Material_32}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.node_id6_Material_32_0_2.geometry}
            material={materials.Material_32}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.node_id6_Material_32_0_3.geometry}
            material={materials.Material_32}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.node_id6_Material_32_0_4.geometry}
            material={materials.Material_32}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.node_id6_Material_32_0_5.geometry}
            material={materials.Material_32}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.node_id9_Material_33_0.geometry}
          material={materials.Material_33}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.node_id12_Material_34_0.geometry}
          material={materials.Material_34}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.node_id12_Material_35_0.geometry}
          material={materials.Material_35}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/cocacola.glb')