/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Jungle Jim (https://sketchfab.com/jungle_jim)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/deep-space-skybox-2d87bae35cff40598c859f2163b4b3b0
Title: Deep Space skybox
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Space(props) {
  const { nodes, materials } = useGLTF('/space.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[1.581, 0.013, 0]}>
        <group rotation={[-Math.PI, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere_Deep_Space_0.geometry}
            material={materials.Deep_Space}
            rotation={[Math.PI / 2, 0, 0]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/space.glb')
