/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Hvenix (https://sketchfab.com/Hvenix)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stone-arch-a54dc19752cf4908aaa32ebf46cee13d
Title: Stone Arch
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function StoneArch(props) {
  const { nodes, materials } = useGLTF('/stone_arch.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.initialShadingGroup}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/stone_arch.glb')